# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  branches:
    include:
    - '*' # build all branches
  paths:
    exclude:
    - forum/file/* # exclude the file, image and police folders
    - forum/image/*
    - forum/police/*


# Use a specific PHP version

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'


# Install dependencies

# - script: composer install --no-interaction --prefer-dist
#   displayName: 'composer install'


# Test with phpunit

# - script: ./phpunit
#   displayName: 'Run tests with phpunit'


# Retain the PHP app with the build record

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(system.defaultWorkingDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1

# This is a comment for demonstration purpose